'use client'

import StyledComponentsRegistry from '@/lib/styled-components/registry';
import { RecoilRoot } from 'recoil';
import { QueryClient, QueryClientProvider } from 'react-query';
import './globals.css';


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const queryClient = new QueryClient()

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>  
            <QueryClientProvider client={queryClient}>
                <RecoilRoot>
                    <StyledComponentsRegistry>
                        <html lang="en">
                            <body>{children}</body>
                        </html>
                    </StyledComponentsRegistry>
                </RecoilRoot>
            </QueryClientProvider>
        </>
    )
}
