import { Container } from "./layout.style"

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
        <Container>
            
        </Container>
        </>
    )
}